Fix split pane issue
pylover/dial-demo pull request #1
Opened 2021-07-18 10:57 UTC by mahsa-yari

2021-07-18 11:05 UTC, pylover commented on src/Dial.svelte
> +<style>
SASS please

2021-07-18 11:06 UTC, pylover requested changes
Please use sass and pre-defined variables.

2021-07-18 11:07 UTC, pylover commented
Take a look at `styles/variables.sass`

2021-07-18 11:35 UTC, mahsa-yari commented on src/Dial.svelte
> +<style>
done

2021-07-18 16:08 UTC, pylover requested changes
Mmmm, not tested yet, waiting to fix all coding and naming issues.

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +    window.addEventListener("mousemove", onMouseMove)
Use `svelte` bind instead of `window.addEventListener`. please respect what you learned recently.

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +  width: 5px;
Use `$gutter` variable.

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +  const onMouseUp = (e) => {
One blank line after each code block such as function or variable definition.

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +  color: $fg;
One blank line after each code block such as class or any selector.

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +    delta = Math.min(Math.max(delta, -lastSeparatorLocation.leftWidth), lastSeparatorLocation.rightWidth)
The maximum allowed chars in each line are 79. 

```python
In [2]: len('    delta = Math.min(Math.max(delta, -lastSeparatorLocation.leftWidth), lastSeparatorLocation.rightWidth)')                                                                                                                       
Out[2]: 105
```

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +  import { onMount } from "svelte"
One blank line after all imports.

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +  let lastSeparatorLocation, left, right
One blank line before each function definition.

2021-07-18 16:08 UTC, pylover commented on src/Dial.svelte
> +  width: 30%;
Semicolon !!! Really?

2021-07-19 08:15 UTC, pylover approved these changes
:1st_place_medal:

2021-07-19 08:16 UTC, merged